// JS function to Find the books on the local computer
// Parameters: dir, directory to look for books
// Writes the output to "books_inital.js" file

const fs = require('fs');
const path = require('path');

const findLocalBooks = (dir) => {

    // Open books_inital.js for Writing
    const outputFilePath = "./seed/books_initial.js"
    fs.writeFileSync(outputFilePath, 
    `//Data generated by ./find_myBooks.js on ${Date().toLocaleString()}\n\nconst raw_data = [\n`, 'utf8')


    // Read the contents of the directory
    const authors = fs.readdirSync(dir);

    authors.forEach(author => {
        const authorPath = path.join(dir, author);

        if (fs.statSync(authorPath).isDirectory()) {

            const books = fs.readdirSync(authorPath);

            books.forEach( book => {

                bookPath = path.join(authorPath, book)
                bookPath = bookPath.replace(/\\/g, '//') // remove escape characters from path

                book = book.replace(/[ -]/g, "+") // replace psaces with '+'

                fs.appendFileSync(outputFilePath, `    {"author": "${author}", "file_name": "${book}", "path": "${bookPath}"},\n`, 'utf8');
            }) 
        }  
    })
    // Close the data array
    fs.appendFileSync(outputFilePath, `]\n\nmodule.exports = raw_data`
    , 'utf-8')
};


module.exports = findLocalBooks